FROM rust:1.71 as build
WORKDIR /ipmon
COPY . .
RUN cargo build --bin ipmon-server --release

FROM debian:bullseye-slim
RUN apt update && apt upgrade -y
RUN apt install -y wget
HEALTHCHECK --interval=5m --timeout=3s \
  CMD wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1
EXPOSE 8080
WORKDIR /app
COPY --from=build /ipmon/target/release/ipmon-server ./
ENTRYPOINT ["/app/ipmon-server"]
