FROM rust:1.84 AS build
RUN apt update && apt upgrade -y
RUN apt install -y g++-aarch64-linux-gnu libc6-dev-arm64-cross
WORKDIR /ipmon
COPY . .
RUN cargo build --bin ipmon --release

FROM debian:bookworm-slim
RUN apt update && apt -y install ca-certificates python3-pip pipx && rm -rf /var/lib/apt/lists/*
RUN pipx install apprise
# pipx bin bath
ENV PATH="$PATH:/root/.local/bin"
WORKDIR /app
COPY --from=build /ipmon/target/release/ipmon ./
ENTRYPOINT ["/app/ipmon"]
