name: client-ci
run-name: Build and Push Client to Docker Hub

on:
  push:
    branches: [ main ]
    paths:
      - 'src/bin/ipmon.rs'
      - 'src/*.rs'
      - 'cargo.toml'
      - 'Dockerfile.client'
      - '.dockerignore'
      - '.github/workflows/*.yml'

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # https://github.com/docker/buildx/issues/495#issuecomment-1043341496
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        id: qemu
        with:
          image: tonistiigi/binfmt:latest
          platforms: linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: |
            linux/arm64

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push ipmon
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.client
          push: true
          tags: psidex/ipmon:latest
          platforms: |
            linux/arm64
