name: server-ci
run-name: Build and Push Server to Docker Hub

on:
  push:
    branches: [ main ]
    paths:
      - 'src/bin/ipmon-server.rs'
      - 'src/*.rs'
      - 'cargo.toml'
      - 'Dockerfile.server'
      - '.dockerignore'
      - '.github/workflows/*.yml'

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: |
            linux/amd64

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push ipmon-server
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.server
          push: true
          tags: psidex/ipmon-server:latest
          platforms: |
            linux/amd64
